# Generated by Django 4.2.28 on 2026-02-17 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_location_listing_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='title',
        ),
    ]
