# Generated by Django 4.2.28 on 2026-02-19 14:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0010_conversation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='photo',
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='First image'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Second image'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Third image'),
        ),
    ]
